frontend: no devDependencies
The TS build on Heroku fails: error TS2503: Cannot find namespace
'React', and I think this is because it’s because it didn’t install
devDependencies because NODE_ENV is production.