boiling the ocean: use of TS project references
Why?

To be able to share logic and constants between frontend and backend
in a way that does not fight TS, or I don’t need to either bring in or write
myself a custom build piepeline. This same sharing mechanism is useful
to share code between page bundles.

Implications

Gave up on relative imports (aka `baseUrl`) because now they don’t seem
to work smoothly with project refs; I don’t often write nor updated them
manually any way.

It looks like I can give up typescript-bundle and instead make use TS’s
`outFile` and `module: amd` instead, then load that into the browser with
the standard Require.js.

Known Issues

I’m yet to figure out how to conveniently do unit tests.

Although the page bundles build and run alright in the browser (through
Require.js), TS reports some error

TS6200: Definitions of the following identifiers conflict with those in
another file

[6:47:39 PM] Building project '/Users/vlad/src/repetitor.tsx/frontend/tsconfig.json'...

frontend/build/home.d.ts:2:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ServerResponseType, ActionName, Wrapper, Title, MainContent, FooterWrapper, DebugLayout, LinkList, TopNavigation, PageLayout, FormContainer, FieldListContainer, FieldContainer, ActionButtonListContainer, Form, PredicateFn, ValidationRules, ValueChangeHandler, InputStyle, Input, Text, ValidationMessage, InputType, TextField, description, InputContainer, EyeButton, GenerateButton, PasswordField, Button, SubmitButton, Container, Checkbox

2 declare module "frontend/shared/src/Reset.css" {
  ~~~~~~~

  frontend/build/inregistrare.d.ts:2:1
    2 declare module "frontend/shared/src/PageRendering" {
      ~~~~~~~
    Conflicts are in this file.

frontend/build/inregistrare.d.ts:2:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ServerResponseType, ActionName, Wrapper, Title, MainContent, FooterWrapper, DebugLayout, LinkList, TopNavigation, PageLayout, FormContainer, FieldListContainer, FieldContainer, ActionButtonListContainer, Form, PredicateFn, ValidationRules, ValueChangeHandler, InputStyle, Input, Text, ValidationMessage, InputType, TextField, description, InputContainer, EyeButton, GenerateButton, PasswordField, Button, SubmitButton, Container, Checkbox

2 declare module "frontend/shared/src/PageRendering" {
  ~~~~~~~

  frontend/build/home.d.ts:2:1
    2 declare module "frontend/shared/src/Reset.css" {
      ~~~~~~~
    Conflicts are in this file.

Found 2 errors.